games = [
    "The Crew: The Quest for Planet Nine",
    "Fluxx",
    "Pit",
    "Chess",
    "Chinese Checkers",
    "Carcassonne",
    "Sushi Go!",
    "Sushi Go Party!",
    "Lords of Waterdeep",
    "Magic Maze",
    "Adult Drinking Games Compendium",
    "Scrabble",
    "Azul",
    "Codenames",
    "Monikers",
    "Exploding Kittens",
    "Dominion",
    "Dominion: Intrigue",
    "Twister",
    "Monopoly Lord of the Rings",
    "Dune",
    "Pictomania",
    "Cockroach Poker",
    "Press Start Pocket Season 1",
    "Press Start Pocket Season 3",
    "Go",
    "Diplomacy",
    "Cranium",
    "Bunny Bunny Moose Moose",
    "Bananagrams",
    "Backgammon",
    "Welcome To...",
    "Santorini",
    "Robinson Crusoe: Adventures on the Cursed Island",
    "Alchemy With Friends",
    "Splendor",
    "Brain Master",
    "More Monikers",
    "Modern Art",
    "Mars 2049",
    "Flamme Rouge",
    "Whitehall Mystery",
    "Forbidden Desert",
    "Funemployed",
    "Decrypto",
    "Unlock!",
    "Pandemic",
    "Concept",
    "Cash 'n Guns",
    "Robinson Crusoe: Treasure Chest",
    "Blood on the Clocktower",
    "Risk",
    "Risk: Global Domination",
    "Santorini",
    "Meeple Circus",
    "The Singing Telegram",
    "Master Detective Game",
    "Risk Lord of the Rings",
    "A Game of Thrones: The Board Game",
    "Clank!",
    "Wavelength",
    "Sagrada",
    "Skull",
    "Brexit: The Card Game",
    "Arboretum",
    "Sushi Go!",
    "Cards Against Humanity",
    "Cards Against Humanity: First Expansion",
    "Vortex",
    "Superfight",
    "El Dorado",
    "Cosmic Encounter",
    "Settlers of Catan",
    "Clue",
    "Concept",
    "Trivial Pursuit",
    "The Quacks of Quedlinburg",
    "Lords of Xidit",
    "Texas Hold 'em",
    "Ticket to Ride",
    "Avalon",
    "Werewolves of Miller's Hollow",
    "Werewords",
    "Settlers of Catan",
    "Settlers of Catan: 5-6 Player Extension",
]
